# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Create release package
on:
  release:
    types: [ published ]
jobs:
  package-release:
    name: Build PowerShell module and add package to release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ 'Release' ]
    env:
      DOTNET_NOLOGO: true
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: '6.0.x'

      - name: Run MSBuild
        run: dotnet msbuild -target:"BuildPowerShellModule" -property:"Configuration=Release" "SmallsOnline.Azure.AVDSetup.csproj"

      - name: Zip module
        shell: pwsh
        run: Compress-Archive -Path "./build/SmallsOnline.Azure.AVDSetup/*" -DestinationPath "./build/SmallsOnline.Azure.AVDSetup.zip" -CompressionLevel "Optimal" -Verbose

      - name: Upload module artifact
        env:
          TAG_RELEASE_API: https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}
          RELEASE_API_URI: https://api.github.com/repos/${{ github.repository }}/releases
        shell: pwsh
        run: $apiHeaders = @{ "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"; } ; $releaseId = (Invoke-RestMethod -Method "Get" -Headers $apiHeaders -Uri $env:TAG_RELEASE_API)[0].id ; Write-Output $releaseId ; Write-Output "$($env:RELEASE_API_URI)/$($releaseId)/assets" ; Invoke-RestMethod -Method "Post" -Uri "$($env:RELEASE_API_URI)/$($releaseId)/assets" -ContentType "application/zip" -Headers $apiHeaders -InFile "./build/SmallsOnline.Azure.AVDSetup.zip" -Verbose
           